version: '2'

services:
  duplicati:
    image: lsioarmhf/duplicati
    container_name: duplicati_container_compose
    restart: always
    ports:
      - '8200:8200'
    volumes:
      - "./config:/config"
      - "/backups:/backups"
      - "/home/brettsalemink/development/Docker/rpi-docker-transmission-open-vpn:/source-rpi-docker-transmission-open-vpn"
      - "/home/brettsalemink/development/Docker/docker-jackett-armhf:/source-docker-jackett-armhf"
    env_file: 
      - ./common.env
    network_mode: "host"
