version: '2'

services:
  duplicati:
    image: lsioarmhf/duplicati
    container_name: duplicati_container_compose
    restart: always
    ports:
      - '8200:8200'
    volumes:
      - "./config:/config"
      - "/backups:/backups"
      - "/home/brettsalemink/development/Docker:/source-slave3-docker"
    env_file: 
      - ./common.env
    network_mode: "host"
